package net.idtoki.serteca.manager;

import java.util.logging.Logger;
import net.idtoki.serteca.model.VehiculoPeer;
import net.idtoki.serteca.group.VehiculoGroupBean;
import net.idtoki.serteca.model.Vehiculo;
import net.zylk.torque.SearchQuery;
import net.zylk.torque.BaseQuery;
import net.zylk.torque.TorqueUtils;
import net.zylk.torque.manager.BaseManager;
import org.apache.torque.TorqueException;
import java.util.Enumeration;


import net.idtoki.serteca.model.Modelo;
import net.idtoki.serteca.model.ModeloPeer;
import net.idtoki.serteca.model.Cliente;
import net.idtoki.serteca.model.ClientePeer;

import org.apache.torque.util.Criteria;
import org.apache.torque.util.UniqueList;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;

/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Jul 03 11:03:24 CEST 2006]
 *
 */
public abstract class BaseVehiculoManager extends BaseManager
{
	protected static final Logger logger = Logger.getLogger(
	   "net.idtoki.serteca.managers.BaseVehiculoManager");

	public static final Criteria buildSearchCriteria(DinamicGridBean dgb)
	{
		return BaseManager.buildSearchCriteria(dgb, new VehiculoManager());
	}

	public static final Criteria buildSearchCriteria(String query, int offset, int limit)
	{
		return BaseManager.buildSearchCriteria(query, offset, limit, new VehiculoManager());
	}

	public static final Criteria buildSearchCriteria(String query)
	{
		return BaseManager.buildSearchCriteria(query, new VehiculoManager());
	}

	protected void addOrSearchCriteria(Criteria criteria,String campo,String valor, String condicion){
		Criteria.Criterion criterion = VehiculoManager.getSearchCriterion(campo,valor, condicion);
		//Si existe ya un criterion hay que utilizarlo para añadir el or sino utilizará un and
		Enumeration enumeration =criteria.elements();
		if(enumeration.hasMoreElements()){
			Criteria.Criterion cr = (Criteria.Criterion) enumeration.nextElement();
			cr.or(criterion);
		}else{
			criteria.or(criterion);
		}
	}

	protected void addAndSearchCriteria(Criteria criteria,String campo, String valor, String condicion){
		Criteria.Criterion criterion = VehiculoManager.getSearchCriterion(campo,valor, condicion);
		criteria.and(criterion);
	}

	protected static Criteria.Criterion getSearchCriterion(String campo,String valor, String condicion){
        Criteria criteria =  new Criteria();
        Criteria.Criterion criterion = null;

			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.MODELO_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.MODELO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.MODELO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.MODELO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.MODELO_ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.VERSION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.VERSION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.VERSION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.VERSION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.VERSION,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.MATRICULA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.MATRICULA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.MATRICULA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.MATRICULA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.MATRICULA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.CLIENTE_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.CLIENTE_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.CLIENTE_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.CLIENTE_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.CLIENTE_ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.CHASIS_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.CHASIS_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.CHASIS_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.CHASIS_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.CHASIS_ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.MOTOR_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.MOTOR_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.MOTOR_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.MOTOR_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.MOTOR_ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.COLOR)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.COLOR,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.COLOR,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.COLOR,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.COLOR,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.FECHA_MATRICULACION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.FECHA_MATRICULACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.FECHA_MATRICULACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.FECHA_MATRICULACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.FECHA_MATRICULACION,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.FECHA_REVISION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.FECHA_REVISION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.FECHA_REVISION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.FECHA_REVISION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.FECHA_REVISION,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(VehiculoPeer.OBSERVACION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,VehiculoPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,VehiculoPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,VehiculoPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,VehiculoPeer.OBSERVACION,valor,true);
		}
									if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ModeloPeer.ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ModeloPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ModeloPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ModeloPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ModeloPeer.ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ModeloPeer.NOMBRE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ModeloPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ModeloPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ModeloPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ModeloPeer.NOMBRE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ModeloPeer.MARCA_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ModeloPeer.MARCA_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ModeloPeer.MARCA_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ModeloPeer.MARCA_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ModeloPeer.MARCA_ID,valor,true);
		}
													if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.NOMBRE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.NOMBRE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.NOMBRECOMERCIAL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.NOMBRECOMERCIAL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.NOMBRECOMERCIAL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.NOMBRECOMERCIAL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.NOMBRECOMERCIAL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.RAZONSOCIAL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.RAZONSOCIAL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.RAZONSOCIAL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.RAZONSOCIAL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.RAZONSOCIAL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.NIF)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.NIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.NIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.NIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.NIF,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.DIRECCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.DIRECCION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.LOCALIDAD_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.LOCALIDAD_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.LOCALIDAD_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.LOCALIDAD_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.LOCALIDAD_ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.CP)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.CP,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.TELEFONO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.TELEFONO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.MOVIL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.MOVIL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.FAX)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.FAX,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.FAX,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.FAX,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.FAX,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.EMAIL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.EMAIL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.FORMA_PAGO_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.FORMA_PAGO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.FORMA_PAGO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.FORMA_PAGO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.FORMA_PAGO_ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.NUMERO_CUENTA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.NUMERO_CUENTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.NUMERO_CUENTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.NUMERO_CUENTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.NUMERO_CUENTA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.DTO_PRONTO_PAGO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.DTO_PRONTO_PAGO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.DTO_PRONTO_PAGO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.DTO_PRONTO_PAGO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.DTO_PRONTO_PAGO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.DIA_PAGO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.DIA_PAGO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.DIA_PAGO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.DIA_PAGO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.DIA_PAGO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ClientePeer.OBSERVACION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ClientePeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ClientePeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ClientePeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ClientePeer.OBSERVACION,valor,true);
		}
						
		return criterion;
	}

	public static final VehiculoGroupBean getVehiculos() {
    	return BaseVehiculoManager.getVehiculos(false);
	}

	public static final VehiculoGroupBean getVehiculos(boolean paginado) {
    	return BaseVehiculoManager.getVehiculos(new Criteria(), paginado,0);
	}

	public static final VehiculoGroupBean getVehiculos(Criteria c) {
		return BaseVehiculoManager.getVehiculos(c,false,0);
	}

	public static final VehiculoGroupBean getVehiculos(Criteria criteria,boolean paginado, int pagina) {
		VehiculoGroupBean objVehiculoGroupBean = new VehiculoGroupBean();
		objVehiculoGroupBean.setPaginaActual(pagina);
		objVehiculoGroupBean.setVehiculos(criteria, paginado);
		return objVehiculoGroupBean;
	}

							
	public static final Vehiculo getVehiculo(int id_Id) {
		Criteria c = new Criteria();
			c.add(VehiculoPeer.ID, id_Id);
			return BaseVehiculoManager.VehiculosGroupBean2Vehiculo(BaseVehiculoManager.getVehiculos(c));
	}

	public static final Vehiculo VehiculosGroupBean2Vehiculo(VehiculoGroupBean obj){
		if(obj.size() == 1)
			return obj.getVehiculo(0);
		else
			return null;
	}

	private static void updateVehiculoAttribute(int id_Id, String valor, String campo) throws Exception
	{
		Vehiculo obj = BaseVehiculoManager.getVehiculo(id_Id);
			if(campo.equals(VehiculoPeer.ID))
					obj.setId(Integer.parseInt(valor)); //int
					if(campo.equals(VehiculoPeer.MODELO_ID))
					obj.setModeloId(Integer.parseInt(valor)); //int
					if(campo.equals(VehiculoPeer.VERSION))
					obj.setVersion(valor); //String
					if(campo.equals(VehiculoPeer.MATRICULA))
					obj.setMatricula(valor); //String
					if(campo.equals(VehiculoPeer.CLIENTE_ID))
					obj.setClienteId(Integer.parseInt(valor)); //int
					if(campo.equals(VehiculoPeer.CHASIS_ID))
					obj.setChasisId(valor); //String
					if(campo.equals(VehiculoPeer.MOTOR_ID))
					obj.setMotorId(valor); //String
					if(campo.equals(VehiculoPeer.COLOR))
					obj.setColor(valor); //String
					if(campo.equals(VehiculoPeer.FECHA_MATRICULACION))
					obj.setFechaMatriculacion(valor); //String
					if(campo.equals(VehiculoPeer.FECHA_REVISION))
					obj.setFechaRevision(valor); //String
					if(campo.equals(VehiculoPeer.OBSERVACION))
					obj.setObs(valor); //String
					obj.save();
	}

	public static void updateId(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.ID);
	}
	public static void updateModeloId(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.MODELO_ID);
	}
	public static void updateVersion(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.VERSION);
	}
	public static void updateMatricula(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.MATRICULA);
	}
	public static void updateClienteId(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.CLIENTE_ID);
	}
	public static void updateChasisId(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.CHASIS_ID);
	}
	public static void updateMotorId(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.MOTOR_ID);
	}
	public static void updateColor(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.COLOR);
	}
	public static void updateFechaMatriculacion(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.FECHA_MATRICULACION);
	}
	public static void updateFechaRevision(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.FECHA_REVISION);
	}
	public static void updateObs(int id_Id, String valor) throws Exception
	{
		updateVehiculoAttribute(id_Id, valor, VehiculoPeer.OBSERVACION);
	}

					public void addJoins(Criteria criteria)
	{
																																																	criteria.addJoin(VehiculoPeer.MODELO_ID,ModeloPeer.ID);
																																																													criteria.addJoin(VehiculoPeer.CLIENTE_ID,ClientePeer.ID);
															}
	

  public static void deleteVehiculo(int id_Id) throws TorqueException
  {
  	VehiculoPeer.doDelete(VehiculoManager.getVehiculo(id_Id));
  }

  public static Vehiculo addUpdateVehiculo(Vehiculo obj) throws TorqueException
  {
	VehiculoGroupBean gb = new VehiculoGroupBean();
	gb.setElemento(obj);
	gb.save();
	return obj;
  }

}

