package net.idtoki.serteca.manager;

import java.util.logging.Logger;
import net.idtoki.serteca.model.OrdenTrabajoPeer;
import net.idtoki.serteca.group.OrdenTrabajoGroupBean;
import net.idtoki.serteca.model.OrdenTrabajo;
import net.zylk.torque.SearchQuery;
import net.zylk.torque.BaseQuery;
import net.zylk.torque.TorqueUtils;
import net.zylk.torque.manager.BaseManager;
import org.apache.torque.TorqueException;
import java.util.Enumeration;


import net.idtoki.serteca.model.Reparacion;
import net.idtoki.serteca.model.ReparacionPeer;
import net.idtoki.serteca.model.Trabajador;
import net.idtoki.serteca.model.TrabajadorPeer;

import org.apache.torque.util.Criteria;
import org.apache.torque.util.UniqueList;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;

/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Jul 03 11:03:24 CEST 2006]
 *
 */
public abstract class BaseOrdenTrabajoManager extends BaseManager
{
	protected static final Logger logger = Logger.getLogger(
	   "net.idtoki.serteca.managers.BaseOrdenTrabajoManager");

	public static final Criteria buildSearchCriteria(DinamicGridBean dgb)
	{
		return BaseManager.buildSearchCriteria(dgb, new OrdenTrabajoManager());
	}

	public static final Criteria buildSearchCriteria(String query, int offset, int limit)
	{
		return BaseManager.buildSearchCriteria(query, offset, limit, new OrdenTrabajoManager());
	}

	public static final Criteria buildSearchCriteria(String query)
	{
		return BaseManager.buildSearchCriteria(query, new OrdenTrabajoManager());
	}

	protected void addOrSearchCriteria(Criteria criteria,String campo,String valor, String condicion){
		Criteria.Criterion criterion = OrdenTrabajoManager.getSearchCriterion(campo,valor, condicion);
		//Si existe ya un criterion hay que utilizarlo para añadir el or sino utilizará un and
		Enumeration enumeration =criteria.elements();
		if(enumeration.hasMoreElements()){
			Criteria.Criterion cr = (Criteria.Criterion) enumeration.nextElement();
			cr.or(criterion);
		}else{
			criteria.or(criterion);
		}
	}

	protected void addAndSearchCriteria(Criteria criteria,String campo, String valor, String condicion){
		Criteria.Criterion criterion = OrdenTrabajoManager.getSearchCriterion(campo,valor, condicion);
		criteria.and(criterion);
	}

	protected static Criteria.Criterion getSearchCriterion(String campo,String valor, String condicion){
        Criteria criteria =  new Criteria();
        Criteria.Criterion criterion = null;

			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.FECHA_ENTRADA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.FECHA_ENTRADA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.FECHA_ENTRADA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.FECHA_ENTRADA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.FECHA_ENTRADA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.FECHA_SALIDA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.FECHA_SALIDA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.FECHA_SALIDA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.FECHA_SALIDA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.FECHA_SALIDA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.OBSERVACION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.OBSERVACION,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.REPARACION_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.REPARACION_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.REPARACION_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.REPARACION_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.REPARACION_ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.IMPORTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.IMPORTE,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.TIPO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.TIPO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.TIPO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.TIPO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.TIPO,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.RESPONSABLE_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.RESPONSABLE_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.RESPONSABLE_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.RESPONSABLE_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.RESPONSABLE_ID,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.HORAS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.HORAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.HORAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.HORAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.HORAS,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OrdenTrabajoPeer.DESCRIPCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OrdenTrabajoPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OrdenTrabajoPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OrdenTrabajoPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OrdenTrabajoPeer.DESCRIPCION,valor,true);
		}
									if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.KM)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.KM,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.KM,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.KM,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.KM,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.DEPOSITO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.DEPOSITO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.DEPOSITO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.DEPOSITO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.DEPOSITO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.FECHA_ENTRADA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.FECHA_ENTRADA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.FECHA_ENTRADA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.FECHA_ENTRADA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.FECHA_ENTRADA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.FECHA_SALIDA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.FECHA_SALIDA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.FECHA_SALIDA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.FECHA_SALIDA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.FECHA_SALIDA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.OBSERVACION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.OBSERVACION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.ESTADOPREVIO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.ESTADOPREVIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.ESTADOPREVIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.ESTADOPREVIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.ESTADOPREVIO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.RESPONSABLE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.RESPONSABLE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.RESPONSABLE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.RESPONSABLE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.RESPONSABLE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.VEHICULO_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.VEHICULO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.VEHICULO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.VEHICULO_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.VEHICULO_ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.IMPORTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.IMPORTE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ReparacionPeer.ESTADO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ReparacionPeer.ESTADO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ReparacionPeer.ESTADO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ReparacionPeer.ESTADO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ReparacionPeer.ESTADO,valor,true);
		}
													if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.NUMERO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.NUMERO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.NUMERO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.NUMERO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.NUMERO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.FECHA_ALTA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.FECHA_ALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.FECHA_ALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.FECHA_ALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.FECHA_ALTA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.FECHA_BAJA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.FECHA_BAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.FECHA_BAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.FECHA_BAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.FECHA_BAJA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.OBSERVACION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.OBSERVACION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.OBSERVACION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.NOMBRE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.NOMBRE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.APELLIDOS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.APELLIDOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.APELLIDOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.APELLIDOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.APELLIDOS,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.APELLIDOSDOS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.APELLIDOSDOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.APELLIDOSDOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.APELLIDOSDOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.APELLIDOSDOS,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.CIF)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.CIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.CIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.CIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.CIF,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.COSTEHORA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.COSTEHORA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.COSTEHORA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.COSTEHORA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.COSTEHORA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.DIRECCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.DIRECCION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.LOCALIDAD_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.LOCALIDAD_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.LOCALIDAD_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.LOCALIDAD_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.LOCALIDAD_ID,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.CP)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.CP,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.TELEFONO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.TELEFONO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.MOVIL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.MOVIL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.EMAIL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.EMAIL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(TrabajadorPeer.CATEGORIA_ID)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,TrabajadorPeer.CATEGORIA_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,TrabajadorPeer.CATEGORIA_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,TrabajadorPeer.CATEGORIA_ID,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,TrabajadorPeer.CATEGORIA_ID,valor,true);
		}
						
		return criterion;
	}

	public static final OrdenTrabajoGroupBean getOrdenTrabajos() {
    	return BaseOrdenTrabajoManager.getOrdenTrabajos(false);
	}

	public static final OrdenTrabajoGroupBean getOrdenTrabajos(boolean paginado) {
    	return BaseOrdenTrabajoManager.getOrdenTrabajos(new Criteria(), paginado,0);
	}

	public static final OrdenTrabajoGroupBean getOrdenTrabajos(Criteria c) {
		return BaseOrdenTrabajoManager.getOrdenTrabajos(c,false,0);
	}

	public static final OrdenTrabajoGroupBean getOrdenTrabajos(Criteria criteria,boolean paginado, int pagina) {
		OrdenTrabajoGroupBean objOrdenTrabajoGroupBean = new OrdenTrabajoGroupBean();
		objOrdenTrabajoGroupBean.setPaginaActual(pagina);
		objOrdenTrabajoGroupBean.setOrdenTrabajos(criteria, paginado);
		return objOrdenTrabajoGroupBean;
	}

							
	public static final OrdenTrabajo getOrdenTrabajo(int id_Id) {
		Criteria c = new Criteria();
			c.add(OrdenTrabajoPeer.ID, id_Id);
			return BaseOrdenTrabajoManager.OrdenTrabajosGroupBean2OrdenTrabajo(BaseOrdenTrabajoManager.getOrdenTrabajos(c));
	}

	public static final OrdenTrabajo OrdenTrabajosGroupBean2OrdenTrabajo(OrdenTrabajoGroupBean obj){
		if(obj.size() == 1)
			return obj.getOrdenTrabajo(0);
		else
			return null;
	}

	private static void updateOrdenTrabajoAttribute(int id_Id, String valor, String campo) throws Exception
	{
		OrdenTrabajo obj = BaseOrdenTrabajoManager.getOrdenTrabajo(id_Id);
			if(campo.equals(OrdenTrabajoPeer.ID))
					obj.setId(Integer.parseInt(valor)); //int
					if(campo.equals(OrdenTrabajoPeer.FECHA_ENTRADA))
					obj.setFechaEntrada(valor); //String
					if(campo.equals(OrdenTrabajoPeer.FECHA_SALIDA))
					obj.setFechaSalida(valor); //String
					if(campo.equals(OrdenTrabajoPeer.OBSERVACION))
					obj.setObs(valor); //String
					if(campo.equals(OrdenTrabajoPeer.REPARACION_ID))
					obj.setReparacionId(Integer.parseInt(valor)); //int
					if(campo.equals(OrdenTrabajoPeer.IMPORTE))
					obj.setImporte(Double.parseDouble(valor)); //double
					if(campo.equals(OrdenTrabajoPeer.TIPO))
					obj.setTipo(Integer.parseInt(valor)); //int
					if(campo.equals(OrdenTrabajoPeer.RESPONSABLE_ID))
					obj.setResponsableId(Integer.parseInt(valor)); //int
					if(campo.equals(OrdenTrabajoPeer.HORAS))
					obj.setHoras(Double.parseDouble(valor)); //double
					if(campo.equals(OrdenTrabajoPeer.DESCRIPCION))
					obj.setDescripcion(valor); //String
					obj.save();
	}

	public static void updateId(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.ID);
	}
	public static void updateFechaEntrada(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.FECHA_ENTRADA);
	}
	public static void updateFechaSalida(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.FECHA_SALIDA);
	}
	public static void updateObs(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.OBSERVACION);
	}
	public static void updateReparacionId(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.REPARACION_ID);
	}
	public static void updateImporte(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.IMPORTE);
	}
	public static void updateTipo(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.TIPO);
	}
	public static void updateResponsableId(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.RESPONSABLE_ID);
	}
	public static void updateHoras(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.HORAS);
	}
	public static void updateDescripcion(int id_Id, String valor) throws Exception
	{
		updateOrdenTrabajoAttribute(id_Id, valor, OrdenTrabajoPeer.DESCRIPCION);
	}

					public void addJoins(Criteria criteria)
	{
																																																	criteria.addJoin(OrdenTrabajoPeer.REPARACION_ID,ReparacionPeer.ID);
																																																													criteria.addJoin(OrdenTrabajoPeer.RESPONSABLE_ID,TrabajadorPeer.ID);
															}
	

  public static void deleteOrdenTrabajo(int id_Id) throws TorqueException
  {
  	OrdenTrabajoPeer.doDelete(OrdenTrabajoManager.getOrdenTrabajo(id_Id));
  }

  public static OrdenTrabajo addUpdateOrdenTrabajo(OrdenTrabajo obj) throws TorqueException
  {
	OrdenTrabajoGroupBean gb = new OrdenTrabajoGroupBean();
	gb.setElemento(obj);
	gb.save();
	return obj;
  }

}

