package net.idtoki.serteca.manager;

import net.idtoki.serteca.model.FacturasPeer;
import net.idtoki.serteca.model.LineaFacturaPeer;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LineaFacturaManager
    extends BaseLineaFacturaManager
{
	public static boolean borraLineaFactura(int idBorrar) {

		Criteria c=new Criteria();
		c.add(LineaFacturaPeer.ID, idBorrar);
		boolean bRet = false;
		try {
			LineaFacturaPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar la LineaFactura");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}	
	
}


