package net.idtoki.serteca.manager;

import net.idtoki.serteca.model.LocalidadPeer;
import net.idtoki.serteca.model.ProvinciaPeer;
import net.zylk.torque.TorqueUtils;
import net.zylk.torque.manager.BaseManager;

import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LocalidadManager
    extends BaseLocalidadManager
{
	/*protected static Criteria.Criterion getSearchCriterion(String campo,String valor){
        Criteria criteria =  new Criteria();
        Criteria.Criterion criterion = null;

			if(campo.equals(BaseManager.campoToLowerCase(LocalidadPeer.NOMBRE)) || campo.equals("all"))
			criterion = TorqueUtils.addOrLikeCriteria(criterion,LocalidadPeer.NOMBRE,valor,true);
						
		return criterion;
	}	
	
	public void addJoins(Criteria criteria)
	{
	}	*/
	
}


