package net.idtoki.serteca.manager;

import net.idtoki.serteca.model.MarcaPeer;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class MarcaManager
    extends BaseMarcaManager
{
	public static boolean borraMarca(int idBorrar) {

		Criteria c=new Criteria();
		c.add(MarcaPeer.ID, idBorrar);
		boolean bRet = false;
		try {
			MarcaPeer.doDelete(c);
			bRet = false;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar la Marca");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}	
}


