package net.idtoki.serteca.model;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue May 16 09:57:47 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class FormaPagoPeer
    extends net.idtoki.serteca.model.BaseFormaPagoPeer
{
}
