
package net.idtoki.serteca.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Modelo
    extends net.idtoki.serteca.model.BaseModelo
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.serteca.model.Modelo");	
	
	public String getNombreModeloParsed()
	{
		return FormatUtils.genericParsedStr(this.getNombre());
	}
	public String getMarcaIdModeloParsed()
	{
		String marca=null;
		try {
			
			marca= this.getMarca().getId() + "-" + this.getMarca().getNombreMarcaParsed();
			//System.out.println("---------marca--"+marca);
		} catch (TorqueException te) {
			logger.severe("No se ha podido localizar la marca. public String getMarcaIdModeloParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(marca);
	}
	public String getIdModeloParsed()
	{
		return new Integer(this.getId()).toString();
	}
	public String getDeleteModelo()
	{
		return "<a href='#' class='eliminar' id='getDeleteModelo" + this.getId() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditModelo()
	{
		return "<a href='#' class='edicion' id='getEditModelo" + this.getId() + "'>&#160;&#160;&#160;&#160;</a>";		
	}		
}
