
package net.idtoki.serteca.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Reparacion
    extends net.idtoki.serteca.model.BaseReparacion
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.serteca.model.Reparacion");
	
	public String getIdReparacionParsed()
	{
		return new Integer(this.getId()).toString();
	}

	public String getFechaEntradaReparacionParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechaEntrada(),"-"));
	}
	
	public String getFechaSalidaReparacionParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechaSalida(),"-"));		
	}
	
/*	public String getFechaSalidaReparacionParsed2()
	{
		String cadena="";
		if (this.getFechaSalida()!=null)
			cadena= FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechaSalida(),"-"));
		return cadena;
	}*/

	public String getVehiculoIdReparacionParsed()
	{
		String vehiculo=null;
		try {
			vehiculo=FormatUtils.genericParsedStr(this.getVehiculo().getId() + "-" + this.getVehiculo().getMatriculaVehiculoParsed());
		} catch (TorqueException te) {
			logger.severe("No se ha podido recoger la Matrícula del Vehiculo. public String getVehiculoIdReparacionParsed()");
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(vehiculo);
	}
	
	public String getVehiculoMatriculaReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getMatricula();
	}
	public String getVehiculoMarcaReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getModelo().getMarca().getNombre();
	}
	public String getVehiculoModeloReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getModelo().getNombre();
	}
	public String getVehiculoChasisIdReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getChasisId();
	}
	public String getClienteIdReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getCliente().getId()+"";
	}	
	public String getClienteNifReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getCliente().getNif();
	}	
	public String getClienteNombreReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getCliente().getNombre();
	}	
	public String getClienteNombreComercialReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getCliente().getNombreComercial();
	}
	public String getClienteTelefonoReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getCliente().getTlfno();
	}	
	public String getClienteMovilReparacionParsed() throws TorqueException
	{
		return this.getVehiculo().getCliente().getMovil();
	}	
	
	public String getObsReparacionParsed()
	{
	String cadena="";
	cadena=FormatUtils.genericParsedStr(this.getObs());
	return cadena;	
	}
	/*
	public String getObsReparacionParsed2()
	{
		String cadena="";
		cadena=FormatUtils.genericParsedStr(this.getObs(),"");
		return cadena;
	}*/
	public String getImporteReparacionParsed()
	{
		return FormatUtils.genericParsedStr(new Float(this.getImporte()).toString());		
	}
	public String getKmReparacionParsed()
	{
		return FormatUtils.genericParsedStr(new Integer(this.getKm()).toString());		
	}
	public String getResponsableReparacionParsed()
	{
		String cadena="";
		cadena=FormatUtils.genericParsedStr(this.getResponsable());
		return cadena;
	}
	public String getDepositoReparacionParsed()
	{
		String cadena="";
		cadena=FormatUtils.genericParsedStr(this.getDeposito());
		return cadena;
	}
	public String getEstadoPrevioReparacionParsed()
	{
		String cadena="";
		cadena=FormatUtils.genericParsedStr(this.getEstadoPrevio());
		return cadena;
	}
/*
	public String getResponsableReparacionParsed2 ()
	{
		String cadena="";
		cadena=FormatUtils.genericParsedStr(this.getResponsable(),"");
		return cadena;
	}*/
	public String getEstadoReparacionParsed()
	{
		String cadena="";
		switch (this.getEstado())
		{
		case 0:
			cadena="<span class='Estilo_00'>Abierta</span>";
			break;
		case 1:
			cadena="<span class='Estilo_01'>En ejecución</span>";
			break;
		case 2:
			cadena="<span class='Estilo_02'>Cerrada</span>";
			break;
		default:
			cadena="<span class='Estilo_03'>n/a</span>";
			break;
		}
		return cadena;
	}
	public String getEstadoReparacionParsedEstilo()
	{
		String cadena="";
		switch (this.getEstado())
		{
		case 0:
			cadena="Abierta_Estilo_00";
			break;
		case 1:
			cadena="En ejecución_Estilo_01";
			break;
		case 2:
			cadena="Cerrada_Estilo_02";
			break;
		default:
			cadena="n/a_Estilo_03";
			break;
		}
		return cadena;
	}	
	public String getDeleteReparacion()
	{
		return "<a href='#' class='eliminar' id='getDeleteReparacion" + this.getId() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditReparacion()
	{
		return "<a href='#' class='edicion' id='getEditReparacion" + this.getId() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
}
