package net.idtoki.serteca.controller;

import java.io.File;
import java.io.IOException;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.idtoki.serteca.group.MarcaGroupBean;
import net.idtoki.serteca.helper.MarcaHelper;
import net.idtoki.serteca.helper.ModeloHelper;
import net.idtoki.serteca.manager.MarcaManager;
import net.idtoki.serteca.model.Marca;
import net.idtoki.serteca.model.MarcaPeer;
import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class MarcaController
    extends net.idtoki.serteca.controller.BaseMarcaController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.serteca.controller.MarcaController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer marca_transformer = null;
 private Transformer marcas_transformer = null;  

 public void init(ServletConfig config)
 {
	  super.init();
	  ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/serteca/app/config/app-config");
	  File marca = new File(resource.getString("app.xsl.templates.dir")+"/PdfMarca.xslt");
	  Source xslSource = new StreamSource(marca);
	  File marcas = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaMarca.xslt");
	  Source xslSourceT = new StreamSource(marcas); 	  
	  try{
		  marca_transformer = tFactory.newTransformer(xslSource);
		  marcas_transformer = tFactory.newTransformer(xslSourceT);		  
	  }catch (Exception e){
	    e.printStackTrace();
	  } 
 }
 public void serviceAddMarca(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
		//recojo los parametros del formulario y doy de alta una nueva marca
	 try
	 {
		 utf8RequestService(request);
		 Marca mr = MarcaHelper.createObj(request);
		 MarcaGroupBean mgb = new MarcaGroupBean();
		 mgb.setElemento(mr);
		 mgb.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }
 
 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 } 
 
 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 		{
 			//c.clear();
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 			{
 			//c.clear();
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

 private Criteria criteriaMarcaTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
 	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
 	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
 	  //System.out.println("----query:"+paramQuery+"----col:"+paramSortCol+"----dir:"+paramSortDir+"----filtro:"+paramFiltro);
 	  c = ordenacion(c,paramSortCol,paramSortDir);
 	 c.addAscendingOrderByColumn(MarcaPeer.NOMBRE);
 	  return c;
 } 
 
 public void  serviceMarcaTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap);
	 Criteria c= MarcaManager.buildSearchCriteria(dgb);
	 c =criteriaMarcaTableContent(request,c);
	 
	 MarcaGroupBean mgb = MarcaManager.getMarcas(c);
	 dgb.setTotalSize(mgb.getTotalSize());
	  
	 String[] methodos= new String[] {			
				 MarcaHelper.NOMBRE_GET_METHOD_NAME+"MarcaParsed",
				 "getEditMarca",
				 "getDeleteMarca"
				 };
	  
	 xmlResponseService(response,AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(
			  										mgb.getAlmacen(),
			  										methodos,
			  										MarcaHelper.ID_GET_METHOD_NAME, dgb,"ISO-8859-1")); 
 }

 public void serviceMarcaUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
			 MarcaHelper.ID_GET_METHOD_NAME,
			 MarcaHelper.NOMBRE_GET_METHOD_NAME
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ModeloHelper().getMarcaIdName());
	 MarcaGroupBean mgb = MarcaManager.getMarcas(MarcaManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, MarcaHelper.COMPLEX_ID_GET_METHOD,"Marca"));
 }
 
 public void serviceDeleteMarca(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
		 if (MarcaManager.borraMarca(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 } 
 
 public void serviceMarcaElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "marcas.ID");
  if (claveId!=-1)
  {
	  c.add(MarcaPeer.ID, claveId);
  }
  c.addAscendingOrderByColumn(MarcaPeer.ID);
  MarcaGroupBean trgb = MarcaManager.getMarcas(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
			  MarcaHelper.ID_GET_METHOD_NAME, 
			  MarcaHelper.NOMBRE_GET_METHOD_NAME+"MarcaParsed"			  
	  			};
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");
  }
  xmlResponseService(response, cadena);
 }  
 
 public void serviceGetMarcaDetalleXml (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
			  MarcaHelper.ID_GET_METHOD_NAME, 
			  MarcaHelper.NOMBRE_GET_METHOD_NAME+"MarcaParsed"
			 };
	  
	 
	 MarcaGroupBean tgb = new MarcaGroupBean();
	 try
	{
		tgb.setElemento(MarcaHelper.getMarca(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	 xmlResponseService(response,tgb.buildXml(getMethodos, null,"ISO-8859-1"));
 }
 
 public void serviceGetMarcaDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
			  MarcaHelper.ID_GET_METHOD_NAME, 
			  MarcaHelper.NOMBRE_GET_METHOD_NAME+"MarcaParsed"
			 };
	  
	 
	 MarcaGroupBean tgb = new MarcaGroupBean();
	 try
	{
		tgb.setElemento(MarcaHelper.getMarca(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), marca_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=marcaDetalle.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();
	
 }  
 
 public void serviceMarcaTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
  Criteria c= new Criteria();
  String paramQuery =  WebUtils.getStringParam(request, "query");
  if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
	  c = MarcaManager.buildSearchCriteria(paramQuery);   
  c =criteriaMarcaTableContent(request,c); 
  MarcaGroupBean tgb = MarcaManager.getMarcas(c);
  
  String[] methodos= new String[] {	
		  MarcaHelper.NOMBRE_GET_METHOD_NAME+"MarcaParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), marcas_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=ListaMarca.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close(); 

 } 
 
}


