package net.idtoki.serteca.controller;

import java.io.IOException;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.idtoki.serteca.group.ProvinciaGroupBean;
import net.idtoki.serteca.helper.ProvinciaHelper;
import net.idtoki.serteca.manager.ProvinciaManager;
import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ProvinciaController
    extends net.idtoki.serteca.controller.BaseProvinciaController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.serteca.controller.ProvinciaController");

 public void init()
 {
  super.init();
  //Aqui se registran los metodos que no se quieran repetir de otros sitios.
  //por ejemplo igual quieres tener los metodos de generacion de ajax
  // en un paquete aparte y no copiarlos por aqui,  sino tenerlos disponibles
  //para todas las aplicaciones sin repetirlos en todos los sitios, pues los registras
  //y punto!!
 }
 
 public void serviceProvinciaUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
			 ProvinciaHelper.ID_GET_METHOD_NAME,
			 ProvinciaHelper.NOMBRE_GET_METHOD_NAME+"ProvinciaParsed"
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 ProvinciaGroupBean pgb = ProvinciaManager.getProvincias(ProvinciaManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(pgb.getAlmacen(),methodos, ProvinciaHelper.COMPLEX_ID_GET_METHOD,"Provincia"));
 }
}


