package net.idtoki.serteca.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import net.idtoki.serteca.group.ClienteGroupBean;
import net.idtoki.serteca.group.ModeloGroupBean;
import net.idtoki.serteca.group.VehiculoGroupBean;
import net.idtoki.serteca.helper.ClienteHelper;
import net.idtoki.serteca.helper.ModeloHelper;
import net.idtoki.serteca.helper.ReparacionHelper;
import net.idtoki.serteca.helper.VehiculoHelper;
import net.idtoki.serteca.manager.ClienteManager;
import net.idtoki.serteca.manager.ModeloManager;
import net.idtoki.serteca.manager.VehiculoCortesiaManager;
import net.idtoki.serteca.manager.VehiculoManager;
import net.idtoki.serteca.model.ClientePeer;
import net.idtoki.serteca.model.ModeloPeer;
import net.idtoki.serteca.model.Vehiculo;
import net.idtoki.serteca.model.VehiculoPeer;
import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class VehiculoController
    extends net.idtoki.serteca.controller.BaseVehiculoController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.serteca.controller.VehiculoController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer vehiculo_transformer = null;  
 private Transformer vehiculos_transformer = null;   

 public void init(ServletConfig config)
 {
	  super.init();
	  ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/serteca/app/config/app-config");
	  File vehiculo = new File(resource.getString("app.xsl.templates.dir")+"/PdfVehiculo.xslt");
	  Source xslSource = new StreamSource(vehiculo);
	  File vehiculos = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaVehiculo.xslt");
	  Source xslSourceT = new StreamSource(vehiculos); 	  
	  try{
		  vehiculo_transformer = tFactory.newTransformer(xslSource);
		  vehiculos_transformer = tFactory.newTransformer(xslSourceT);			  
	  }catch (Exception e){
	    e.printStackTrace();
	  }  
 }
 
 public void serviceAddVehiculo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
		//recojo los parametros del formulario y doy de alta un nuevo vehiculo
	 utf8RequestService(request);
	 try
	 {
		 Vehiculo vh = VehiculoHelper.createObj(request);
		 vh.setFechaMatriculacion(FormatUtils.ddmmaaaa2aaaammdd(vh.getFechaMatriculacion(),"-",""));
		 vh.setFechaRevision(FormatUtils.ddmmaaaa2aaaammdd(vh.getFechaRevision(),"-",""));
		 VehiculoGroupBean vgb = new VehiculoGroupBean();
		 vgb.setElemento(vh);
		 vgb.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }
 
 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 }
  
 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 		{
 			//c.clear();
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 			{
 			//c.clear();
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

 private Criteria criteriaVehiculoTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
	 String param =  WebUtils.getStringParam(request, new ClienteHelper().getIdName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,VehiculoPeer.CLIENTE_ID,param);	
	 param =  WebUtils.getStringParam(request, new ModeloHelper().getIdName());
	 if(param != null)
		 TorqueUtils.addEqualCriteria(c,VehiculoPeer.MODELO_ID,param);		 
 	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
 	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
 	  //System.out.println("----query:"+paramQuery+"----col:"+paramSortCol+"----dir:"+paramSortDir+"----filtro:"+paramFiltro);
 	  c = ordenacion(c,paramSortCol,paramSortDir);

 	  return c;
 } 
 
 public void  serviceVehiculoTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =VehiculoManager.buildSearchCriteria(dgb); 
	 c =criteriaVehiculoTableContent(request,c);
	 
	 VehiculoGroupBean vgb = VehiculoManager.getVehiculos(c);
	 dgb.setTotalSize(vgb.getTotalSize());
	  
	 String[] methodos= new String[] { 
			 VehiculoHelper.MATRICULA_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CLIENTE_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.MODELO_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.COLOR_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CHASIS_ID_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.FECHA_MATRICULACION_GET_METHOD_NAME + "VehiculoParsed",	
			 VehiculoHelper.MOTOR_ID_GET_METHOD_NAME + "VehiculoParsed",
			 "getEditVehiculo",
			 "getDeleteVehiculo"
	 };
	  
	 xmlResponseService(response,AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(
			  										vgb.getAlmacen(),
			  										methodos,
			  										VehiculoHelper.ID_GET_METHOD_NAME, dgb,"ISO-8859-1")); 
 }
 
 public void serviceVehiculoUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
			 VehiculoHelper.ID_GET_METHOD_NAME, 
			 VehiculoHelper.MATRICULA_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.CLIENTE_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.MODELO_ID_GET_METHOD_NAME+"VehiculoParsed"
			 };

	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new ReparacionHelper().getVehiculoIdName());	 
	 VehiculoGroupBean vgb = VehiculoManager.getVehiculos(VehiculoManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(vgb.getAlmacen(),methodos, VehiculoHelper.COMPLEX_ID_GET_METHOD,"Vehiculo"));
 }
 
 /*protected StringBuffer updateFechaMatriculacionResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(VehiculoManager.getVehiculo( 
    			Integer.parseInt(a.get(0).toString())).getFechaMatriculacionParsed());
   }*/

 /*protected String updateFechaMatriculacionRequestCallBack(String value)
 {
  return FormatUtils.ddmmaaaa2aaaammdd(value, "-","");
  }*/

 protected StringBuffer updateClienteIdResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(VehiculoManager.getVehiculo(Integer.parseInt(a.get(0).toString())).getClienteIdVehiculoParsed());
   }
 protected StringBuffer updateModeloIdResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(VehiculoManager.getVehiculo(Integer.parseInt(a.get(0).toString())).getModeloIdVehiculoParsed());
   }
 
 protected StringBuffer updateMotorIdResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(VehiculoManager.getVehiculo(Integer.parseInt(a.get(0).toString())).getMotorIdVehiculoParsed());
   }
 
 protected StringBuffer updateColorResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(VehiculoManager.getVehiculo(Integer.parseInt(a.get(0).toString())).getColorVehiculoParsed());
   }
 
 public void serviceDeleteVehiculo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
		 if (VehiculoManager.borraVehiculo(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));
 } 
 
 public void serviceVehiculoElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "vehiculos.ID");
  if (claveId!=-1)
  {
	  c.add(VehiculoPeer.ID, claveId);
  }
  c.addAscendingOrderByColumn(VehiculoPeer.ID);
  VehiculoGroupBean trgb = VehiculoManager.getVehiculos(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
				 VehiculoHelper.ID_GET_METHOD_NAME, 
				 VehiculoHelper.VERSION_GET_METHOD_NAME + "VehiculoParsed",
				 VehiculoHelper.MATRICULA_GET_METHOD_NAME + "VehiculoParsed",
				 VehiculoHelper.CLIENTE_ID_GET_METHOD_NAME+"VehiculoParsed",
				 VehiculoHelper.MODELO_ID_GET_METHOD_NAME+"VehiculoParsed",
				 VehiculoHelper.COLOR_GET_METHOD_NAME + "VehiculoParsed",
				 VehiculoHelper.OBSERVACION_GET_METHOD_NAME + "VehiculoParsed",
				 VehiculoHelper.CHASIS_ID_GET_METHOD_NAME + "VehiculoParsed",
				 VehiculoHelper.FECHA_MATRICULACION_GET_METHOD_NAME + "VehiculoParsed",	
				 VehiculoHelper.FECHA_REVISION_GET_METHOD_NAME+ "VehiculoParsed",
				 VehiculoHelper.MOTOR_ID_GET_METHOD_NAME + "VehiculoParsed"
	  			};
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");
  }
  xmlResponseService(response, cadena);
 }  
 
 public void serviceVehiculoCliente(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "Clientes.ID");
  if (claveId!=-1)
  {
	  c.add(ClientePeer.ID, claveId);
  }
  c.addAscendingOrderByColumn(ClientePeer.ID);
  ClienteGroupBean trgb = ClienteManager.getClientes(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><Vehiculos.CLIENTE_ID>" + trgb.getCliente(0).getId() + "-" + trgb.getCliente(0).getNombreClienteParsed() + "</Vehiculos.CLIENTE_ID></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }
 
 public void serviceVehiculoModelo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "Modelos.ID");
  if (claveId!=-1)
  {
	  c.add(ModeloPeer.ID, claveId);
  }
  c.addAscendingOrderByColumn(ModeloPeer.ID);
  ModeloGroupBean trgb = ModeloManager.getModelos(c);
  
  if (trgb.getTotalSize()!=0)
  {	
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
  	  cadena = cadena + "<result><Vehiculos.MODELO_ID>" + trgb.getModelo(0).getId() + "-" + trgb.getModelo(0).getNombreModeloParsed() + "</Vehiculos.MODELO_ID></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 } 
 
 public void serviceGetVehiculoDetalleXml (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
			 VehiculoHelper.ID_GET_METHOD_NAME, 
			 VehiculoHelper.VERSION_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.MATRICULA_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CLIENTE_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.MODELO_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.COLOR_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.OBSERVACION_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CHASIS_ID_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.FECHA_MATRICULACION_GET_METHOD_NAME + "VehiculoParsed",	
			 VehiculoHelper.MOTOR_ID_GET_METHOD_NAME + "VehiculoParsed"
			 };
	  
	 
	 VehiculoGroupBean tgb = new VehiculoGroupBean();
	 try
	{
		tgb.setElemento(VehiculoHelper.getVehiculo(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	 xmlResponseService(response,tgb.buildXml(getMethodos, null,"ISO-8859-1"));
 }
 
 public void serviceGetVehiculoDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
			 VehiculoHelper.ID_GET_METHOD_NAME, 
			 VehiculoHelper.VERSION_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.MATRICULA_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CLIENTE_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.MODELO_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.COLOR_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.OBSERVACION_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CHASIS_ID_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.FECHA_MATRICULACION_GET_METHOD_NAME + "VehiculoParsed",	
			 VehiculoHelper.MOTOR_ID_GET_METHOD_NAME + "VehiculoParsed"
			 };
	  
	 
	 VehiculoGroupBean tgb = new VehiculoGroupBean();
	 try
	{
		tgb.setElemento(VehiculoHelper.getVehiculo(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), vehiculo_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=vehiculoDetalle.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();
	
 }  
 
 public void serviceVehiculoTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
  Criteria c= new Criteria();
  String paramQuery =  WebUtils.getStringParam(request, "query");
  if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
	  c = VehiculoManager.buildSearchCriteria(paramQuery);   
  c =criteriaVehiculoTableContent(request,c);	  
  VehiculoGroupBean tgb = VehiculoManager.getVehiculos(c);
  
  String[] methodos= new String[] {	
			 VehiculoHelper.VERSION_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.MATRICULA_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CLIENTE_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.MODELO_ID_GET_METHOD_NAME+"VehiculoParsed",
			 VehiculoHelper.COLOR_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.OBSERVACION_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.CHASIS_ID_GET_METHOD_NAME + "VehiculoParsed",
			 VehiculoHelper.FECHA_MATRICULACION_GET_METHOD_NAME + "VehiculoParsed",	
			 VehiculoHelper.MOTOR_ID_GET_METHOD_NAME + "VehiculoParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), vehiculos_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=ListaVehiculo.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();

 }    
 
}


