package net.idtoki.serteca.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.serteca.model.ProvinciaPeer;
import net.idtoki.serteca.model.Provincia;
import net.idtoki.serteca.manager.ProvinciaManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Jul 03 11:03:24 CEST 2006]
 *
 */
public abstract class BaseProvinciaHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private Provincia obj;
	public static final String ID_GET_METHOD_NAME = "getId";
	public static final String NOMBRE_GET_METHOD_NAME = "getNombre";


	public BaseProvinciaHelper()
	{
		this.obj = new Provincia();
	}

	public BaseProvinciaHelper(Provincia obj)
	{
		this.obj = obj;
	}


	public String getIdHTMLAttrs()
	{
		return " name=\"" + getIdName() + "\" " +
			   "id=\"" + getIdId() + "\" " +
			   "value=\"" + getIdValue() + "\" ";
	 }

	public String getIdId()
	{
		return getIdId(obj);
	}

	private static String getIdId(Provincia o)
	{
		return ProvinciaPeer.ID;
	}

	public String getIdName()
	{
		return getIdName(obj);
	}

	private static String getIdName(Provincia o)
	{
		return ProvinciaPeer.ID;
	}

	public String getIdValue()
	{
		return getIdValue(obj);
	}

	private static String getIdValue(Provincia o)
	{
			return "" + o.getId();
		}

	public String getNombreHTMLAttrs()
	{
		return " name=\"" + getNombreName() + "\" " +
			   "id=\"" + getNombreId() + "\" " +
			   "value=\"" + getNombreValue() + "\" ";
	 }

	public String getNombreId()
	{
		return getNombreId(obj);
	}

	private static String getNombreId(Provincia o)
	{
		return ProvinciaPeer.NOMBRE;
	}

	public String getNombreName()
	{
		return getNombreName(obj);
	}

	private static String getNombreName(Provincia o)
	{
		return ProvinciaPeer.NOMBRE;
	}

	public String getNombreValue()
	{
		return getNombreValue(obj);
	}

	private static String getNombreValue(Provincia o)
	{
			if(o.getNombre() != null)
			return "" + o.getNombre();
		else
			return "";
		}

	public static Provincia getProvincia(HttpServletRequest req) throws TorqueException
	{
										
		int id_Id = WebUtils.getintParam(req, getIdName(new Provincia()));

	
		Provincia o = new Provincia();
		if((id_Id >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = ProvinciaManager.getProvincia(id_Id);
		}
		return o;
	}

	public static Provincia createObj(HttpServletRequest req) throws TorqueException
	{
		Provincia o =  BaseProvinciaHelper.getProvincia(req);
			 o.setId(WebUtils.getintParam(req, getIdName(o)));
		
			 o.setNombre(WebUtils.getStringParam(req, getNombreName(o)));
		
			return o;
	}
}
