package net.idtoki.serteca.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.serteca.model.OrdenTrabajoPeer;
import net.idtoki.serteca.model.OrdenTrabajo;
import net.idtoki.serteca.manager.OrdenTrabajoManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Jul 03 11:03:24 CEST 2006]
 *
 */
public abstract class BaseOrdenTrabajoHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private OrdenTrabajo obj;
	public static final String ID_GET_METHOD_NAME = "getId";
	public static final String FECHA_ENTRADA_GET_METHOD_NAME = "getFechaEntrada";
	public static final String FECHA_SALIDA_GET_METHOD_NAME = "getFechaSalida";
	public static final String OBSERVACION_GET_METHOD_NAME = "getObs";
	public static final String REPARACION_ID_GET_METHOD_NAME = "getReparacionId";
	public static final String IMPORTE_GET_METHOD_NAME = "getImporte";
	public static final String TIPO_GET_METHOD_NAME = "getTipo";
	public static final String RESPONSABLE_ID_GET_METHOD_NAME = "getResponsableId";
	public static final String HORAS_GET_METHOD_NAME = "getHoras";
	public static final String DESCRIPCION_GET_METHOD_NAME = "getDescripcion";


	public BaseOrdenTrabajoHelper()
	{
		this.obj = new OrdenTrabajo();
	}

	public BaseOrdenTrabajoHelper(OrdenTrabajo obj)
	{
		this.obj = obj;
	}


	public String getIdHTMLAttrs()
	{
		return " name=\"" + getIdName() + "\" " +
			   "id=\"" + getIdId() + "\" " +
			   "value=\"" + getIdValue() + "\" ";
	 }

	public String getIdId()
	{
		return getIdId(obj);
	}

	private static String getIdId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.ID;
	}

	public String getIdName()
	{
		return getIdName(obj);
	}

	private static String getIdName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.ID;
	}

	public String getIdValue()
	{
		return getIdValue(obj);
	}

	private static String getIdValue(OrdenTrabajo o)
	{
			return "" + o.getId();
		}

	public String getFechaEntradaHTMLAttrs()
	{
		return " name=\"" + getFechaEntradaName() + "\" " +
			   "id=\"" + getFechaEntradaId() + "\" " +
			   "value=\"" + getFechaEntradaValue() + "\" ";
	 }

	public String getFechaEntradaId()
	{
		return getFechaEntradaId(obj);
	}

	private static String getFechaEntradaId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.FECHA_ENTRADA;
	}

	public String getFechaEntradaName()
	{
		return getFechaEntradaName(obj);
	}

	private static String getFechaEntradaName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.FECHA_ENTRADA;
	}

	public String getFechaEntradaValue()
	{
		return getFechaEntradaValue(obj);
	}

	private static String getFechaEntradaValue(OrdenTrabajo o)
	{
			if(o.getFechaEntrada() != null)
			return "" + o.getFechaEntrada();
		else
			return "";
		}

	public String getFechaSalidaHTMLAttrs()
	{
		return " name=\"" + getFechaSalidaName() + "\" " +
			   "id=\"" + getFechaSalidaId() + "\" " +
			   "value=\"" + getFechaSalidaValue() + "\" ";
	 }

	public String getFechaSalidaId()
	{
		return getFechaSalidaId(obj);
	}

	private static String getFechaSalidaId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.FECHA_SALIDA;
	}

	public String getFechaSalidaName()
	{
		return getFechaSalidaName(obj);
	}

	private static String getFechaSalidaName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.FECHA_SALIDA;
	}

	public String getFechaSalidaValue()
	{
		return getFechaSalidaValue(obj);
	}

	private static String getFechaSalidaValue(OrdenTrabajo o)
	{
			if(o.getFechaSalida() != null)
			return "" + o.getFechaSalida();
		else
			return "";
		}

	public String getObsHTMLAttrs()
	{
		return " name=\"" + getObsName() + "\" " +
			   "id=\"" + getObsId() + "\" " +
			   "value=\"" + getObsValue() + "\" ";
	 }

	public String getObsId()
	{
		return getObsId(obj);
	}

	private static String getObsId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.OBSERVACION;
	}

	public String getObsName()
	{
		return getObsName(obj);
	}

	private static String getObsName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.OBSERVACION;
	}

	public String getObsValue()
	{
		return getObsValue(obj);
	}

	private static String getObsValue(OrdenTrabajo o)
	{
			if(o.getObs() != null)
			return "" + o.getObs();
		else
			return "";
		}

	public String getReparacionIdHTMLAttrs()
	{
		return " name=\"" + getReparacionIdName() + "\" " +
			   "id=\"" + getReparacionIdId() + "\" " +
			   "value=\"" + getReparacionIdValue() + "\" ";
	 }

	public String getReparacionIdId()
	{
		return getReparacionIdId(obj);
	}

	private static String getReparacionIdId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.REPARACION_ID;
	}

	public String getReparacionIdName()
	{
		return getReparacionIdName(obj);
	}

	private static String getReparacionIdName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.REPARACION_ID;
	}

	public String getReparacionIdValue()
	{
		return getReparacionIdValue(obj);
	}

	private static String getReparacionIdValue(OrdenTrabajo o)
	{
			return "" + o.getReparacionId();
		}

	public String getImporteHTMLAttrs()
	{
		return " name=\"" + getImporteName() + "\" " +
			   "id=\"" + getImporteId() + "\" " +
			   "value=\"" + getImporteValue() + "\" ";
	 }

	public String getImporteId()
	{
		return getImporteId(obj);
	}

	private static String getImporteId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.IMPORTE;
	}

	public String getImporteName()
	{
		return getImporteName(obj);
	}

	private static String getImporteName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.IMPORTE;
	}

	public String getImporteValue()
	{
		return getImporteValue(obj);
	}

	private static String getImporteValue(OrdenTrabajo o)
	{
			return "" + o.getImporte();
		}

	public String getTipoHTMLAttrs()
	{
		return " name=\"" + getTipoName() + "\" " +
			   "id=\"" + getTipoId() + "\" " +
			   "value=\"" + getTipoValue() + "\" ";
	 }

	public String getTipoId()
	{
		return getTipoId(obj);
	}

	private static String getTipoId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.TIPO;
	}

	public String getTipoName()
	{
		return getTipoName(obj);
	}

	private static String getTipoName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.TIPO;
	}

	public String getTipoValue()
	{
		return getTipoValue(obj);
	}

	private static String getTipoValue(OrdenTrabajo o)
	{
			return "" + o.getTipo();
		}

	public String getResponsableIdHTMLAttrs()
	{
		return " name=\"" + getResponsableIdName() + "\" " +
			   "id=\"" + getResponsableIdId() + "\" " +
			   "value=\"" + getResponsableIdValue() + "\" ";
	 }

	public String getResponsableIdId()
	{
		return getResponsableIdId(obj);
	}

	private static String getResponsableIdId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.RESPONSABLE_ID;
	}

	public String getResponsableIdName()
	{
		return getResponsableIdName(obj);
	}

	private static String getResponsableIdName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.RESPONSABLE_ID;
	}

	public String getResponsableIdValue()
	{
		return getResponsableIdValue(obj);
	}

	private static String getResponsableIdValue(OrdenTrabajo o)
	{
			return "" + o.getResponsableId();
		}

	public String getHorasHTMLAttrs()
	{
		return " name=\"" + getHorasName() + "\" " +
			   "id=\"" + getHorasId() + "\" " +
			   "value=\"" + getHorasValue() + "\" ";
	 }

	public String getHorasId()
	{
		return getHorasId(obj);
	}

	private static String getHorasId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.HORAS;
	}

	public String getHorasName()
	{
		return getHorasName(obj);
	}

	private static String getHorasName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.HORAS;
	}

	public String getHorasValue()
	{
		return getHorasValue(obj);
	}

	private static String getHorasValue(OrdenTrabajo o)
	{
			return "" + o.getHoras();
		}

	public String getDescripcionHTMLAttrs()
	{
		return " name=\"" + getDescripcionName() + "\" " +
			   "id=\"" + getDescripcionId() + "\" " +
			   "value=\"" + getDescripcionValue() + "\" ";
	 }

	public String getDescripcionId()
	{
		return getDescripcionId(obj);
	}

	private static String getDescripcionId(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.DESCRIPCION;
	}

	public String getDescripcionName()
	{
		return getDescripcionName(obj);
	}

	private static String getDescripcionName(OrdenTrabajo o)
	{
		return OrdenTrabajoPeer.DESCRIPCION;
	}

	public String getDescripcionValue()
	{
		return getDescripcionValue(obj);
	}

	private static String getDescripcionValue(OrdenTrabajo o)
	{
			if(o.getDescripcion() != null)
			return "" + o.getDescripcion();
		else
			return "";
		}

	public static OrdenTrabajo getOrdenTrabajo(HttpServletRequest req) throws TorqueException
	{
										
		int id_Id = WebUtils.getintParam(req, getIdName(new OrdenTrabajo()));

	
		OrdenTrabajo o = new OrdenTrabajo();
		if((id_Id >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = OrdenTrabajoManager.getOrdenTrabajo(id_Id);
		}
		return o;
	}

	public static OrdenTrabajo createObj(HttpServletRequest req) throws TorqueException
	{
		OrdenTrabajo o =  BaseOrdenTrabajoHelper.getOrdenTrabajo(req);
			 o.setId(WebUtils.getintParam(req, getIdName(o)));
		
			 o.setFechaEntrada(WebUtils.getStringParam(req, getFechaEntradaName(o)));
		
			 o.setFechaSalida(WebUtils.getStringParam(req, getFechaSalidaName(o)));
		
			 o.setObs(WebUtils.getStringParam(req, getObsName(o)));
		
			 		o.setReparacionId(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getReparacionIdName(o)))));
		
			 o.setImporte(WebUtils.getdoubleParam(req, getImporteName(o)));
		
			 o.setTipo(WebUtils.getintParam(req, getTipoName(o)));
		
			 		o.setResponsableId(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getResponsableIdName(o)))));
		
			 o.setHoras(WebUtils.getdoubleParam(req, getHorasName(o)));
		
			 o.setDescripcion(WebUtils.getStringParam(req, getDescripcionName(o)));
		
			return o;
	}
}
