package net.idtoki.serteca.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.serteca.model.LocalidadPeer;
import net.idtoki.serteca.model.Localidad;
import net.idtoki.serteca.manager.LocalidadManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Jul 03 11:03:24 CEST 2006]
 *
 */
public abstract class BaseLocalidadHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private Localidad obj;
	public static final String ID_GET_METHOD_NAME = "getId";
	public static final String PROVINCIA_ID_GET_METHOD_NAME = "getProvinciaId";
	public static final String NOMBRE_GET_METHOD_NAME = "getNombre";


	public BaseLocalidadHelper()
	{
		this.obj = new Localidad();
	}

	public BaseLocalidadHelper(Localidad obj)
	{
		this.obj = obj;
	}


	public String getIdHTMLAttrs()
	{
		return " name=\"" + getIdName() + "\" " +
			   "id=\"" + getIdId() + "\" " +
			   "value=\"" + getIdValue() + "\" ";
	 }

	public String getIdId()
	{
		return getIdId(obj);
	}

	private static String getIdId(Localidad o)
	{
		return LocalidadPeer.ID;
	}

	public String getIdName()
	{
		return getIdName(obj);
	}

	private static String getIdName(Localidad o)
	{
		return LocalidadPeer.ID;
	}

	public String getIdValue()
	{
		return getIdValue(obj);
	}

	private static String getIdValue(Localidad o)
	{
			return "" + o.getId();
		}

	public String getProvinciaIdHTMLAttrs()
	{
		return " name=\"" + getProvinciaIdName() + "\" " +
			   "id=\"" + getProvinciaIdId() + "\" " +
			   "value=\"" + getProvinciaIdValue() + "\" ";
	 }

	public String getProvinciaIdId()
	{
		return getProvinciaIdId(obj);
	}

	private static String getProvinciaIdId(Localidad o)
	{
		return LocalidadPeer.PROVINCIA_ID;
	}

	public String getProvinciaIdName()
	{
		return getProvinciaIdName(obj);
	}

	private static String getProvinciaIdName(Localidad o)
	{
		return LocalidadPeer.PROVINCIA_ID;
	}

	public String getProvinciaIdValue()
	{
		return getProvinciaIdValue(obj);
	}

	private static String getProvinciaIdValue(Localidad o)
	{
			return "" + o.getProvinciaId();
		}

	public String getNombreHTMLAttrs()
	{
		return " name=\"" + getNombreName() + "\" " +
			   "id=\"" + getNombreId() + "\" " +
			   "value=\"" + getNombreValue() + "\" ";
	 }

	public String getNombreId()
	{
		return getNombreId(obj);
	}

	private static String getNombreId(Localidad o)
	{
		return LocalidadPeer.NOMBRE;
	}

	public String getNombreName()
	{
		return getNombreName(obj);
	}

	private static String getNombreName(Localidad o)
	{
		return LocalidadPeer.NOMBRE;
	}

	public String getNombreValue()
	{
		return getNombreValue(obj);
	}

	private static String getNombreValue(Localidad o)
	{
			if(o.getNombre() != null)
			return "" + o.getNombre();
		else
			return "";
		}

	public static Localidad getLocalidad(HttpServletRequest req) throws TorqueException
	{
										
		int id_Id = WebUtils.getintParam(req, getIdName(new Localidad()));

	
		Localidad o = new Localidad();
		if((id_Id >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = LocalidadManager.getLocalidad(id_Id);
		}
		return o;
	}

	public static Localidad createObj(HttpServletRequest req) throws TorqueException
	{
		Localidad o =  BaseLocalidadHelper.getLocalidad(req);
			 o.setId(WebUtils.getintParam(req, getIdName(o)));
		
			 		o.setProvinciaId(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getProvinciaIdName(o)))));
		
			 o.setNombre(WebUtils.getStringParam(req, getNombreName(o)));
		
			return o;
	}
}
