package net.idtoki.serteca.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.serteca.model.FacturasPeer;
import net.idtoki.serteca.model.Facturas;
import net.idtoki.serteca.manager.FacturasManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Jul 03 11:03:24 CEST 2006]
 *
 */
public abstract class BaseFacturasHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private Facturas obj;
	public static final String ID_GET_METHOD_NAME = "getId";
	public static final String FECHA_GET_METHOD_NAME = "getFechaIni";
	public static final String IMPORTE_GET_METHOD_NAME = "getImporte";
	public static final String ESTADO_GET_METHOD_NAME = "getEstado";
	public static final String DESCRIPCION_GET_METHOD_NAME = "getDescripcion";
	public static final String OBSERVACION_GET_METHOD_NAME = "getObs";
	public static final String CLIENTE_ID_GET_METHOD_NAME = "getClienteId";
	public static final String REPARACION_ID_GET_METHOD_NAME = "getReparacionId";


	public BaseFacturasHelper()
	{
		this.obj = new Facturas();
	}

	public BaseFacturasHelper(Facturas obj)
	{
		this.obj = obj;
	}


	public String getIdHTMLAttrs()
	{
		return " name=\"" + getIdName() + "\" " +
			   "id=\"" + getIdId() + "\" " +
			   "value=\"" + getIdValue() + "\" ";
	 }

	public String getIdId()
	{
		return getIdId(obj);
	}

	private static String getIdId(Facturas o)
	{
		return FacturasPeer.ID;
	}

	public String getIdName()
	{
		return getIdName(obj);
	}

	private static String getIdName(Facturas o)
	{
		return FacturasPeer.ID;
	}

	public String getIdValue()
	{
		return getIdValue(obj);
	}

	private static String getIdValue(Facturas o)
	{
			return "" + o.getId();
		}

	public String getFechaIniHTMLAttrs()
	{
		return " name=\"" + getFechaIniName() + "\" " +
			   "id=\"" + getFechaIniId() + "\" " +
			   "value=\"" + getFechaIniValue() + "\" ";
	 }

	public String getFechaIniId()
	{
		return getFechaIniId(obj);
	}

	private static String getFechaIniId(Facturas o)
	{
		return FacturasPeer.FECHA;
	}

	public String getFechaIniName()
	{
		return getFechaIniName(obj);
	}

	private static String getFechaIniName(Facturas o)
	{
		return FacturasPeer.FECHA;
	}

	public String getFechaIniValue()
	{
		return getFechaIniValue(obj);
	}

	private static String getFechaIniValue(Facturas o)
	{
			if(o.getFechaIni() != null)
			return "" + o.getFechaIni();
		else
			return "";
		}

	public String getImporteHTMLAttrs()
	{
		return " name=\"" + getImporteName() + "\" " +
			   "id=\"" + getImporteId() + "\" " +
			   "value=\"" + getImporteValue() + "\" ";
	 }

	public String getImporteId()
	{
		return getImporteId(obj);
	}

	private static String getImporteId(Facturas o)
	{
		return FacturasPeer.IMPORTE;
	}

	public String getImporteName()
	{
		return getImporteName(obj);
	}

	private static String getImporteName(Facturas o)
	{
		return FacturasPeer.IMPORTE;
	}

	public String getImporteValue()
	{
		return getImporteValue(obj);
	}

	private static String getImporteValue(Facturas o)
	{
			return "" + o.getImporte();
		}

	public String getEstadoHTMLAttrs()
	{
		return " name=\"" + getEstadoName() + "\" " +
			   "id=\"" + getEstadoId() + "\" " +
			   "value=\"" + getEstadoValue() + "\" ";
	 }

	public String getEstadoId()
	{
		return getEstadoId(obj);
	}

	private static String getEstadoId(Facturas o)
	{
		return FacturasPeer.ESTADO;
	}

	public String getEstadoName()
	{
		return getEstadoName(obj);
	}

	private static String getEstadoName(Facturas o)
	{
		return FacturasPeer.ESTADO;
	}

	public String getEstadoValue()
	{
		return getEstadoValue(obj);
	}

	private static String getEstadoValue(Facturas o)
	{
			return "" + o.getEstado();
		}

	public String getDescripcionHTMLAttrs()
	{
		return " name=\"" + getDescripcionName() + "\" " +
			   "id=\"" + getDescripcionId() + "\" " +
			   "value=\"" + getDescripcionValue() + "\" ";
	 }

	public String getDescripcionId()
	{
		return getDescripcionId(obj);
	}

	private static String getDescripcionId(Facturas o)
	{
		return FacturasPeer.DESCRIPCION;
	}

	public String getDescripcionName()
	{
		return getDescripcionName(obj);
	}

	private static String getDescripcionName(Facturas o)
	{
		return FacturasPeer.DESCRIPCION;
	}

	public String getDescripcionValue()
	{
		return getDescripcionValue(obj);
	}

	private static String getDescripcionValue(Facturas o)
	{
			if(o.getDescripcion() != null)
			return "" + o.getDescripcion();
		else
			return "";
		}

	public String getObsHTMLAttrs()
	{
		return " name=\"" + getObsName() + "\" " +
			   "id=\"" + getObsId() + "\" " +
			   "value=\"" + getObsValue() + "\" ";
	 }

	public String getObsId()
	{
		return getObsId(obj);
	}

	private static String getObsId(Facturas o)
	{
		return FacturasPeer.OBSERVACION;
	}

	public String getObsName()
	{
		return getObsName(obj);
	}

	private static String getObsName(Facturas o)
	{
		return FacturasPeer.OBSERVACION;
	}

	public String getObsValue()
	{
		return getObsValue(obj);
	}

	private static String getObsValue(Facturas o)
	{
			if(o.getObs() != null)
			return "" + o.getObs();
		else
			return "";
		}

	public String getClienteIdHTMLAttrs()
	{
		return " name=\"" + getClienteIdName() + "\" " +
			   "id=\"" + getClienteIdId() + "\" " +
			   "value=\"" + getClienteIdValue() + "\" ";
	 }

	public String getClienteIdId()
	{
		return getClienteIdId(obj);
	}

	private static String getClienteIdId(Facturas o)
	{
		return FacturasPeer.CLIENTE_ID;
	}

	public String getClienteIdName()
	{
		return getClienteIdName(obj);
	}

	private static String getClienteIdName(Facturas o)
	{
		return FacturasPeer.CLIENTE_ID;
	}

	public String getClienteIdValue()
	{
		return getClienteIdValue(obj);
	}

	private static String getClienteIdValue(Facturas o)
	{
			return "" + o.getClienteId();
		}

	public String getReparacionIdHTMLAttrs()
	{
		return " name=\"" + getReparacionIdName() + "\" " +
			   "id=\"" + getReparacionIdId() + "\" " +
			   "value=\"" + getReparacionIdValue() + "\" ";
	 }

	public String getReparacionIdId()
	{
		return getReparacionIdId(obj);
	}

	private static String getReparacionIdId(Facturas o)
	{
		return FacturasPeer.REPARACION_ID;
	}

	public String getReparacionIdName()
	{
		return getReparacionIdName(obj);
	}

	private static String getReparacionIdName(Facturas o)
	{
		return FacturasPeer.REPARACION_ID;
	}

	public String getReparacionIdValue()
	{
		return getReparacionIdValue(obj);
	}

	private static String getReparacionIdValue(Facturas o)
	{
			return "" + o.getReparacionId();
		}

	public static Facturas getFacturas(HttpServletRequest req) throws TorqueException
	{
										
		int id_Id = WebUtils.getintParam(req, getIdName(new Facturas()));

	
		Facturas o = new Facturas();
		if((id_Id >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = FacturasManager.getFacturas(id_Id);
		}
		return o;
	}

	public static Facturas createObj(HttpServletRequest req) throws TorqueException
	{
		Facturas o =  BaseFacturasHelper.getFacturas(req);
			 o.setId(WebUtils.getintParam(req, getIdName(o)));
		
			 o.setFechaIni(WebUtils.getStringParam(req, getFechaIniName(o)));
		
			 o.setImporte(WebUtils.getdoubleParam(req, getImporteName(o)));
		
			 o.setEstado(WebUtils.getintParam(req, getEstadoName(o)));
		
			 o.setDescripcion(WebUtils.getStringParam(req, getDescripcionName(o)));
		
			 o.setObs(WebUtils.getStringParam(req, getObsName(o)));
		
			 		o.setClienteId(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getClienteIdName(o)))));
		
			 		o.setReparacionId(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getReparacionIdName(o)))));
		
			return o;
	}
}
