package net.idtoki.serteca.helper;

import net.idtoki.serteca.model.Categoria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon May 22 10:54:32 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class CategoriaHelper
    extends net.idtoki.serteca.helper.BaseCategoriaHelper
{
		    			public CategoriaHelper()
    {
        super();
    }
    public CategoriaHelper(Categoria obj)
    {
        super(obj);
    }
}


