package net.idtoki.serteca.helper;

import net.idtoki.serteca.model.Provincia;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ProvinciaHelper
    extends net.idtoki.serteca.helper.BaseProvinciaHelper
{
		    			public ProvinciaHelper()
    {
        super();
    }
    public ProvinciaHelper(Provincia obj)
    {
        super(obj);
    }
}


