package net.idtoki.serteca.helper;

import net.idtoki.serteca.model.Reparacion;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ReparacionHelper
    extends net.idtoki.serteca.helper.BaseReparacionHelper
{
		    			public ReparacionHelper()
    {
        super();
    }
    public ReparacionHelper(Reparacion obj)
    {
        super(obj);
    }
}


