package net.idtoki.serteca.model.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Mon Jul 03 11:03:24 CEST 2006]
  *
  */
public class OrdenTrabajoMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "net.idtoki.serteca.model.map.OrdenTrabajoMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("SERTECA-DB");

        dbMap.addTable("Ordenes_Trabajo");
        TableMap tMap = dbMap.getTable("Ordenes_Trabajo");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);

        // this might need upgrading based on what all the databases
        // need, but for now assume one parameter.
          tMap.setPrimaryKeyMethodInfo("Ordenes_Trabajo_id_seq");

              tMap.addPrimaryKey("Ordenes_Trabajo.ID", new Integer(0));
                    tMap.addColumn("Ordenes_Trabajo.FECHA_ENTRADA", "");
                    tMap.addColumn("Ordenes_Trabajo.FECHA_SALIDA", "");
                    tMap.addColumn("Ordenes_Trabajo.OBSERVACION", "");
                    tMap.addForeignKey(
                "Ordenes_Trabajo.REPARACION_ID", new Integer(0) , "Reparaciones" ,
                "id");
                    tMap.addColumn("Ordenes_Trabajo.IMPORTE", new Double(0));
                    tMap.addColumn("Ordenes_Trabajo.TIPO", new Integer(0));
                    tMap.addForeignKey(
                "Ordenes_Trabajo.RESPONSABLE_ID", new Integer(0) , "Trabajadores" ,
                "id");
                    tMap.addColumn("Ordenes_Trabajo.HORAS", new Double(0));
                    tMap.addColumn("Ordenes_Trabajo.DESCRIPCION", "");
          }
}
