package net.idtoki.serteca.app.event;

import java.util.logging.Logger;

import net.zylk.web.listener.BaseServletContextListener;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 01 12:46:43 CET 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class OnStartUp extends BaseServletContextListener
{
 private static final Logger logger = Logger.getLogger("net.idtoki.serteca.app.event.OnStartUp");

  public String getConfigFilePath() {
  return "net/idtoki/serteca/app/config/app-config";
 }
}


